[package]
name = "proxmox-backup"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]
edition = "2018"

[lib]
name = "proxmox_backup"
path = "src/lib.rs"

[dependencies]
base64 = "0.10"
bytes = "0.4"
chrono = "0.4" # Date and time library for Rust
crc32fast = "1"
endian_trait = { version = "0.6", features = ["arrays"] }
failure = "0.1"
futures-preview = "0.3.0-alpha"
h2 = { version = "0.2.0-alpha.1", features = ["stream"] }
http = "0.1"
hyper = { version = "0.13.0-alpha.1" }
lazy_static = "1.3"
libc = "0.2"
log = "0.4"
mio = "0.6"
native-tls = "0.2"
nix = "0.15"
openssl = "0.10"
pam = "0.7"
pam-sys = "0.5"
pin-utils = "0.1.0-alpha"
proxmox = { git = "ssh://gitolite3@proxdev.maurer-it.com/rust/proxmox", version = "0.1" }
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellwords = "1.0"
siphasher = "0.3"
syslog = "4.0"
textwrap = "0.11"
tokio = { version = "0.2.0-alpha.4" }
tokio-executor = { version = "0.2.0-alpha.4" }
tokio-net = { version = "0.2.0-alpha.4", features = ["signal"] }
tokio-openssl = "0.4.0-alpha.2"
tower-service = "0.3.0-alpha.1"
url = "1.7"
valgrind_request = { version = "1.1", optional = true }
walkdir = "2"
xdg = "2.2"
zstd = "0.4"

[features]
default = []
valgrind = ["valgrind_request"]

[replace]
"zstd-sys:1.4.13" = { path = "zstd-sys" }
