[package]
name = "apitest"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]


[lib]
name = "apitest"
path = "src/lib.rs"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]


[dependencies]
failure = "0.1.3"
phf = "0.7.23"
phf_macros = "0.7.23"
derive-new = "0.5.5"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
hyper = "0.12.13"
