[package]
name = "apitest"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]


[lib]
name = "json_schema"
path = "src/lib.rs"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]


[dependencies]
failure = "0.1.3"  
phf = "0.7.23"  
phf_macros = "0.7.23"  
derive-new = "0.5.5" 
serde = "1.0.80"                          # A generic serialization/deserialization framework
serde_json = "1.0.32"                     # A JSON serialization file format
serde_derive = "1.0.80"
