[package]
name = "apitest"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]
edition = "2018"

[lib]
name = "apitest"
path = "src/lib.rs"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]


[dependencies]
failure = "0.1.3"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
url = "1.7.1"
futures = "0.1.25"
tokio = "0.1.11"
tokio-codec = "0.1.1"
http = "0.1.13"
hyper = "0.12.14"
lazy_static = "1.1.0"
regex = "1.0.6"
rust-crypto = "0.2.36"
libc = "0.2"