[package]
name = "apitest"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]


[lib]
name = "apitest"
path = "src/lib.rs"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]


[dependencies]
failure = "0.1.3"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
url = "1.7.1"
hyper = "0.12.13"
