[package]
name = "proxmox-backup"
version = "0.1.0"
authors = ["Dietmar Maurer <dietmar@proxmox.com>"]
edition = "2018"

[lib]
name = "proxmox_backup"
path = "src/lib.rs"

[dependencies]
proxmox = { path = "../proxmox/proxmox" }
proxmox-protocol = { path = "proxmox-protocol" }
log = "0.4"
syslog = "4.0"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.7"
futures = "0.1"
bytes = "0.4"
tokio-threadpool = "0.1"
tokio = "0.1"
tokio-fs = "0.1"
tokio-tls = "0.2"
tokio-signal = "0.2"
native-tls = "0.2"
http = "0.1"
h2 = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
lazy_static = "1.1"
regex = "1.0"
libc = "0.2"
nix = "0.13"
shellwords = "1.0"
uuid = { version = "0.7", features = ["v4"] }
chrono = "0.4" # Date and time library for Rust
openssl = "0.10"
siphasher = "0.3"
endian_trait = { version = "0.6", features = ["arrays"] }
walkdir = "2"
md5 = "0.6"
base64 = "0.10"
pam-sys = "0.5"
pam = "0.7"
zstd = "0.4"
xdg = "2.2"
mio = "0.6"
valgrind_request = { version = "1.1", optional = true }
textwrap = "0.11"

[features]
default = []
valgrind = ["valgrind_request"]

[replace]
"zstd-sys:1.4.10" = { path = "zstd-sys" }
