[package]
name = "proxmox-file-restore"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
futures = "0.3"
libc = "0.2"
nix = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.6", features = [ "io-std", "rt", "rt-multi-thread", "time" ] }

pxar = { version = "0.10.1", features = [ "tokio-io" ] }

#proxmox = { version = "0.15.3" }
proxmox-async = "0.4"
proxmox-lang = "1.1"
proxmox-router = { version = "1.2.4", features = [ "cli" ] }
proxmox-schema = { version = "1.3.1", features = [ "api-macro" ] }
proxmox-time = "1"
proxmox-uuid = "1"
proxmox-sys = "0.3"

pbs-api-types = { path = "../pbs-api-types" }
pbs-buildcfg = { path = "../pbs-buildcfg" }
pbs-config = { path = "../pbs-config" }
pbs-client = { path = "../pbs-client" }
pbs-datastore = { path = "../pbs-datastore" }
pbs-tools = { path = "../pbs-tools" }
