[package]
name = "proxmox-backup-banner"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"

[dependencies]
proxmox = { version = "0.11.5", default-features = false, features = [] }
