[package]
name = "pxar-bin"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"

[[bin]]
name = "pxar"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
futures = "0.3"
nix = "0.24"
serde_json = "1.0"
tokio = { version = "1.6", features = [ "rt", "rt-multi-thread" ] }

pathpatterns = "0.1.2"
#proxmox = "0.15.3"
proxmox-async = "0.4"
proxmox-schema = { version = "1.3.1", features = [ "api-macro" ] }
proxmox-router = "1.2.4"
proxmox-sys = "0.3"
pxar = { version = "0.10.1", features = [ "tokio-io" ] }

pbs-client = { path = "../pbs-client" }
pbs-tools = { path = "../pbs-tools" }
