[package]
name = "pbs-tape"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
description = "LTO tape support"

[dependencies]
lazy_static = "1.4"
libc = "0.2"
log = "0.4"
anyhow = "1.0"
thiserror = "1.0"
endian_trait = { version = "0.6", features = ["arrays"] }
hex = "0.4.3"
nix = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bitflags = "1.2.1"
regex = "1.5"
udev = "0.4"

proxmox-io = "1"
proxmox-lang = "1.1"
# api-macro is only used by the binaries, so maybe we should split them out
proxmox-schema = { version = "1.3.1", features = [ "api-macro" ] }
proxmox-time = "1"
proxmox-uuid = "1"

# router::cli is only used by binaries, so maybe we should split them out
proxmox-router = "1.2.4"
proxmox-sys = "0.3.1"

pbs-api-types = { path = "../pbs-api-types" }
pbs-config = { path = "../pbs-config" }
