overlay = "."
crate_src_path = ".."
whitelist = ["tests/*.c"]

# needed for pinutils alpha
allow_prerelease_deps = true

[source]
# TODO: update once public
vcs_git = ""
vcs_browser = ""
maintainer = "Proxmox Support Team <support@proxmox.com>"
section = "admin"
build_depends = [
  "debhelper (>= 12~)",
  "bash-completion",
  "pve-eslint",
  "python3-docutils",
  "python3-pygments",
  "rsync",
  "fonts-dejavu-core <!nodoc>",
  "fonts-lato <!nodoc>",
  "fonts-open-sans <!nodoc>",
  "graphviz <!nodoc>",
  "latexmk <!nodoc>",
  "python3-sphinx <!nodoc>",
  "texlive-fonts-extra <!nodoc>",
  "texlive-fonts-recommended <!nodoc>",
  "texlive-xetex <!nodoc>",
  "xindy <!nodoc>",
]
build_depends_excludes = [
  "debhelper (>=11)",
]

[packages.lib]
depends = [
  "libacl1-dev",
  "libfuse3-dev",
  "libsystemd-dev",
  "uuid-dev",
]
