[package]
name = "proxmox-rrd"
version = "0.1.0"
authors = ["Proxmox Support Team <support@proxmox.com>"]
edition = "2018"
description = "Simple RRD database implementation."

[dependencies]
anyhow = "1.0"
bitflags = "1.2.1"
log = "0.4"

proxmox = { version = "0.14.0", features = ["api-macro"] }

proxmox-rrd-api-types = { path = "../proxmox-rrd-api-types" }
